services:
  json-server:
    image: clue/json-server
    ports:
      - "3000:80"
    volumes:
      - ./db.json:/data/db.json
    command: -H 0.0.0.0 /data/db.json

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      SWAGGER_JSON: /swagger/swagger.json
    volumes:
      - ./swagger.json:/swagger/swagger.json
